from __future__ import annotations

from datetime import datetime
from typing import Protocol

from updater.domain.models import Target, TargetVersion, TargetVulnerability, VendorConfig, Vulnerability


class TargetRepository(Protocol):
    def upsert(self, target: Target) -> Target: ...
    def list_all(self) -> list[Target]: ...
    def find_by_name(self, name: str) -> Target | None: ...
    def delete(self, name: str) -> bool: ...
    def delete_all(self) -> int: ...


class TargetVersionRepository(Protocol):
    def upsert(self, version: TargetVersion) -> TargetVersion: ...
    def delete_all(self) -> int: ...
    def find_latest(self, target_id: str) -> TargetVersion | None: ...
    def set_current(
        self, target_id: str, *, version: str, source_url: str | None, previous_version: str | None
    ) -> TargetVersion: ...
    def mark_seen(self, target_id: str, *, version: str) -> None: ...
    def list_recent_changes(self, since: datetime) -> list[TargetVersion]: ...


class VendorConfigRepository(Protocol):
    def upsert(self, config: VendorConfig) -> VendorConfig: ...
    def find_by_vendor(self, vendor: str) -> VendorConfig | None: ...
    def find_by_target(self, target: Target) -> VendorConfig | None: ...
    def list_all(self) -> list[VendorConfig]: ...
    def delete(self, vendor: str) -> bool: ...


class VulnerabilityRepository(Protocol):
    def upsert(self, vulnerability: Vulnerability) -> Vulnerability: ...
    def list_all(self) -> list[Vulnerability]: ...
    def delete(self, vulnerability_id: str) -> bool: ...
    def delete_all(self) -> int: ...


class TargetVulnerabilityRepository(Protocol):
    def upsert(self, link: TargetVulnerability) -> TargetVulnerability: ...
    def list_all(self) -> list[TargetVulnerability]: ...
    def delete_by_target(self, target_id: str) -> int: ...
    def delete_all(self) -> int: ...


class VulnerabilitySource(Protocol):
    source_name: str

    def search(
        self, target: Target, query: str, since_year: int | None = None
    ) -> list[tuple[Vulnerability, dict]]: ...
