from __future__ import annotations

from typing import Protocol

from updater.domain.models import Target, TargetVersion, TargetVulnerability, Vulnerability


class TargetRepository(Protocol):
    def upsert(self, target: Target) -> Target: ...
    def list_all(self) -> list[Target]: ...
    def find_by_name(self, name: str) -> Target | None: ...
    def delete(self, name: str) -> bool: ...


class TargetVersionRepository(Protocol):
    def upsert(self, version: TargetVersion) -> TargetVersion: ...


class VulnerabilityRepository(Protocol):
    def upsert(self, vulnerability: Vulnerability) -> Vulnerability: ...
    def list_all(self) -> list[Vulnerability]: ...


class TargetVulnerabilityRepository(Protocol):
    def upsert(self, link: TargetVulnerability) -> TargetVulnerability: ...
    def list_all(self) -> list[TargetVulnerability]: ...
    def delete_by_target(self, target_id: str) -> int: ...


class VulnerabilitySource(Protocol):
    source_name: str

    def search(
        self, target: Target, query: str, since_year: int | None = None
    ) -> list[tuple[Vulnerability, dict]]: ...
